services:
  postgres:
    image: postgres:18.0-alpine
    container_name: eventee-postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: eventee
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventee-network

  redis:
    image: redis:7.0
    container_name: eventee-redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - eventee-network

volumes:
  postgres_data:

networks:
  eventee-network:
    driver: bridge